copy-windows:
  stage: deploy
  tags:
    - windows
  script:
    - md -Force "E:/dev/Crow"
    - cp include\* -Destination E:/dev/Crow\ -Recurse -Force -Exclude .git

copy-linux:
  stage: deploy
  tags:
    - linux
  script:
    - if [ ! -d ~/crow ]; then mkdir ~/crow; fi
    - cp -r include/. ~/crow
